# Generated by Django 6.0.7 on 2026-07-19 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('manager_forecast', 'Прогноз менеджера'), ('actual_sales', 'Фактические продажи'), ('sales_plan', 'План продаж'), ('other', 'Другой файл')], default='manager_forecast', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
