# Generated by Django 6.0.7 on 2026-07-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='forecast_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прогноза'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='manager',
            field=models.CharField(blank=True, choices=[('khusnutdinov', 'Хуснутдинов А.'), ('redko', 'Редько В.'), ('izmailov', 'Измайлов М.'), ('mustafin', 'Мустафин Р.'), ('polyakov', 'Поляков А.'), ('prasolov_soloviev', 'Прасолов и Соловьёв'), ('fomichev', 'Фомичев В.'), ('khoroshevsky', 'Хорошевский А.'), ('tsarev', 'Царёв М.'), ('ushakov', 'Ушаков А.')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('manager_forecast', 'План и прогноз менеджера'), ('actual_sales', 'Фактические продажи'), ('other', 'Другой файл')], default='manager_forecast', max_length=30),
        ),
    ]
