# Generated by Django 6.0.7 on 2026-07-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadedfile_forecast_date_uploadedfile_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='column_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='sheet_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='validation_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='validation_status',
            field=models.CharField(choices=[('not_checked', 'Не проверен'), ('valid', 'Проверен'), ('warning', 'Есть предупреждения'), ('error', 'Ошибка')], default='not_checked', max_length=20),
        ),
    ]
